TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dhp30330.db
DATA += dhp30330.proto

#=======================================
include $(TOP)/configure/RULES
